services:
  web:
    image: crpi-zp6yheeplqxsff50.cn-hangzhou.personal.cr.aliyuncs.com/sax-qaq/view-card-sites:latest
    container_name: view-card-sites
    restart: unless-stopped
    ports:
      - "80:3000"
